POST http://127.0.0.1:10002/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "id": "login",
  "password": "1234"
}
###
POST http://localhost:10002/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "id": "abc",
  "password": "1234"
}
###
GET http://localhost:10002/api/v1/user HTTP/1.1
Cookie: connect.sid=s%3AZL3rO3heN7Q4iJtI3D6PtU6aVxwGdDZR.oDruZKvfW0rEc9Z43Nef%2Fh3Nuf%2FbIGf8w70uWl9dock; Path=/; Expires=Fri, 19 Nov 2021 16:44:13 GMT; HttpOnly
###
POST http://localhost:10002/api/v1/file/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="chaewon.jpg"
Content-Type: image/jpeg

< ./chaewon.jpg
--WebAppBoundary--